/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CordycepinRouteImport } from './routes/cordycepin'
import { Route as CordycepsCultivationRouteImport } from './routes/cordyceps-cultivation'
import { Route as CordycepsFaqRouteImport } from './routes/cordyceps-faq'
import { Route as CordycepsHealthBenefitsRouteImport } from './routes/cordyceps-health-benefits'
import { Route as CordycepsVsSinensisRouteImport } from './routes/cordyceps-vs-sinensis'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ContactIndexRouteImport } from './routes/contact/index'
import { Route as CordycepsStudyIndexRouteImport } from './routes/cordyceps-study/index'
import { Route as CultivationTrainingIndexRouteImport } from './routes/cultivation-training/index'
import { Route as ResearchKnowledgeIndexRouteImport } from './routes/research-knowledge/index'
import { Route as WhyRadhvanIndexRouteImport } from './routes/why-radhvan/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CordycepinRoute = CordycepinRouteImport.update({
  id: '/cordycepin',
  path: '/cordycepin',
  getParentRoute: () => rootRouteImport,
} as any)
const CordycepsCultivationRoute = CordycepsCultivationRouteImport.update({
  id: '/cordyceps-cultivation',
  path: '/cordyceps-cultivation',
  getParentRoute: () => rootRouteImport,
} as any)
const CordycepsFaqRoute = CordycepsFaqRouteImport.update({
  id: '/cordyceps-faq',
  path: '/cordyceps-faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CordycepsHealthBenefitsRoute = CordycepsHealthBenefitsRouteImport.update({
  id: '/cordyceps-health-benefits',
  path: '/cordyceps-health-benefits',
  getParentRoute: () => rootRouteImport,
} as any)
const CordycepsVsSinensisRoute = CordycepsVsSinensisRouteImport.update({
  id: '/cordyceps-vs-sinensis',
  path: '/cordyceps-vs-sinensis',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactIndexRoute = ContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRouteImport,
} as any)
const CordycepsStudyIndexRoute = CordycepsStudyIndexRouteImport.update({
  id: '/cordyceps-study/',
  path: '/cordyceps-study/',
  getParentRoute: () => rootRouteImport,
} as any)
const CultivationTrainingIndexRoute =
  CultivationTrainingIndexRouteImport.update({
    id: '/cultivation-training/',
    path: '/cultivation-training/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ResearchKnowledgeIndexRoute = ResearchKnowledgeIndexRouteImport.update({
  id: '/research-knowledge/',
  path: '/research-knowledge/',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyRadhvanIndexRoute = WhyRadhvanIndexRouteImport.update({
  id: '/why-radhvan/',
  path: '/why-radhvan/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cordycepin': typeof CordycepinRoute
  '/cordyceps-cultivation': typeof CordycepsCultivationRoute
  '/cordyceps-faq': typeof CordycepsFaqRoute
  '/cordyceps-health-benefits': typeof CordycepsHealthBenefitsRoute
  '/cordyceps-vs-sinensis': typeof CordycepsVsSinensisRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/contact/': typeof ContactIndexRoute
  '/cordyceps-study/': typeof CordycepsStudyIndexRoute
  '/cultivation-training/': typeof CultivationTrainingIndexRoute
  '/research-knowledge/': typeof ResearchKnowledgeIndexRoute
  '/why-radhvan/': typeof WhyRadhvanIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cordycepin': typeof CordycepinRoute
  '/cordyceps-cultivation': typeof CordycepsCultivationRoute
  '/cordyceps-faq': typeof CordycepsFaqRoute
  '/cordyceps-health-benefits': typeof CordycepsHealthBenefitsRoute
  '/cordyceps-vs-sinensis': typeof CordycepsVsSinensisRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/contact': typeof ContactIndexRoute
  '/cordyceps-study': typeof CordycepsStudyIndexRoute
  '/cultivation-training': typeof CultivationTrainingIndexRoute
  '/research-knowledge': typeof ResearchKnowledgeIndexRoute
  '/why-radhvan': typeof WhyRadhvanIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cordycepin': typeof CordycepinRoute
  '/cordyceps-cultivation': typeof CordycepsCultivationRoute
  '/cordyceps-faq': typeof CordycepsFaqRoute
  '/cordyceps-health-benefits': typeof CordycepsHealthBenefitsRoute
  '/cordyceps-vs-sinensis': typeof CordycepsVsSinensisRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/contact/': typeof ContactIndexRoute
  '/cordyceps-study/': typeof CordycepsStudyIndexRoute
  '/cultivation-training/': typeof CultivationTrainingIndexRoute
  '/research-knowledge/': typeof ResearchKnowledgeIndexRoute
  '/why-radhvan/': typeof WhyRadhvanIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cordycepin'
    | '/cordyceps-cultivation'
    | '/cordyceps-faq'
    | '/cordyceps-health-benefits'
    | '/cordyceps-vs-sinensis'
    | '/sitemap.xml'
    | '/contact/'
    | '/cordyceps-study/'
    | '/cultivation-training/'
    | '/research-knowledge/'
    | '/why-radhvan/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cordycepin'
    | '/cordyceps-cultivation'
    | '/cordyceps-faq'
    | '/cordyceps-health-benefits'
    | '/cordyceps-vs-sinensis'
    | '/sitemap.xml'
    | '/contact'
    | '/cordyceps-study'
    | '/cultivation-training'
    | '/research-knowledge'
    | '/why-radhvan'
  id:
    | '__root__'
    | '/'
    | '/cordycepin'
    | '/cordyceps-cultivation'
    | '/cordyceps-faq'
    | '/cordyceps-health-benefits'
    | '/cordyceps-vs-sinensis'
    | '/sitemap.xml'
    | '/contact/'
    | '/cordyceps-study/'
    | '/cultivation-training/'
    | '/research-knowledge/'
    | '/why-radhvan/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CordycepinRoute: typeof CordycepinRoute
  CordycepsCultivationRoute: typeof CordycepsCultivationRoute
  CordycepsFaqRoute: typeof CordycepsFaqRoute
  CordycepsHealthBenefitsRoute: typeof CordycepsHealthBenefitsRoute
  CordycepsVsSinensisRoute: typeof CordycepsVsSinensisRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ContactIndexRoute: typeof ContactIndexRoute
  CordycepsStudyIndexRoute: typeof CordycepsStudyIndexRoute
  CultivationTrainingIndexRoute: typeof CultivationTrainingIndexRoute
  ResearchKnowledgeIndexRoute: typeof ResearchKnowledgeIndexRoute
  WhyRadhvanIndexRoute: typeof WhyRadhvanIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cordycepin': {
      id: '/cordycepin'
      path: '/cordycepin'
      fullPath: '/cordycepin'
      preLoaderRoute: typeof CordycepinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cordyceps-cultivation': {
      id: '/cordyceps-cultivation'
      path: '/cordyceps-cultivation'
      fullPath: '/cordyceps-cultivation'
      preLoaderRoute: typeof CordycepsCultivationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cordyceps-faq': {
      id: '/cordyceps-faq'
      path: '/cordyceps-faq'
      fullPath: '/cordyceps-faq'
      preLoaderRoute: typeof CordycepsFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cordyceps-health-benefits': {
      id: '/cordyceps-health-benefits'
      path: '/cordyceps-health-benefits'
      fullPath: '/cordyceps-health-benefits'
      preLoaderRoute: typeof CordycepsHealthBenefitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cordyceps-vs-sinensis': {
      id: '/cordyceps-vs-sinensis'
      path: '/cordyceps-vs-sinensis'
      fullPath: '/cordyceps-vs-sinensis'
      preLoaderRoute: typeof CordycepsVsSinensisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact/'
      preLoaderRoute: typeof ContactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cordyceps-study/': {
      id: '/cordyceps-study/'
      path: '/cordyceps-study'
      fullPath: '/cordyceps-study/'
      preLoaderRoute: typeof CordycepsStudyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cultivation-training/': {
      id: '/cultivation-training/'
      path: '/cultivation-training'
      fullPath: '/cultivation-training/'
      preLoaderRoute: typeof CultivationTrainingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research-knowledge/': {
      id: '/research-knowledge/'
      path: '/research-knowledge'
      fullPath: '/research-knowledge/'
      preLoaderRoute: typeof ResearchKnowledgeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-radhvan/': {
      id: '/why-radhvan/'
      path: '/why-radhvan'
      fullPath: '/why-radhvan/'
      preLoaderRoute: typeof WhyRadhvanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CordycepinRoute: CordycepinRoute,
  CordycepsCultivationRoute: CordycepsCultivationRoute,
  CordycepsFaqRoute: CordycepsFaqRoute,
  CordycepsHealthBenefitsRoute: CordycepsHealthBenefitsRoute,
  CordycepsVsSinensisRoute: CordycepsVsSinensisRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ContactIndexRoute: ContactIndexRoute,
  CordycepsStudyIndexRoute: CordycepsStudyIndexRoute,
  CultivationTrainingIndexRoute: CultivationTrainingIndexRoute,
  ResearchKnowledgeIndexRoute: ResearchKnowledgeIndexRoute,
  WhyRadhvanIndexRoute: WhyRadhvanIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
