/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CordycepinRouteImport } from './routes/cordycepin'
import { Route as CordycepsCultivationRouteImport } from './routes/cordyceps-cultivation'
import { Route as CordycepsFaqRouteImport } from './routes/cordyceps-faq'
import { Route as CordycepsHealthBenefitsRouteImport } from './routes/cordyceps-health-benefits'
import { Route as CordycepsStudyRouteImport } from './routes/cordyceps-study'
import { Route as CordycepsVsSinensisRouteImport } from './routes/cordyceps-vs-sinensis'
import { Route as CultivationTrainingRouteImport } from './routes/cultivation-training'
import { Route as ResearchKnowledgeRouteImport } from './routes/research-knowledge'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as WhyRadhvanRouteImport } from './routes/why-radhvan'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CordycepinRoute = CordycepinRouteImport.update({
  id: '/cordycepin',
  path: '/cordycepin',
  getParentRoute: () => rootRouteImport,
} as any)
const CordycepsCultivationRoute = CordycepsCultivationRouteImport.update({
  id: '/cordyceps-cultivation',
  path: '/cordyceps-cultivation',
  getParentRoute: () => rootRouteImport,
} as any)
const CordycepsFaqRoute = CordycepsFaqRouteImport.update({
  id: '/cordyceps-faq',
  path: '/cordyceps-faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CordycepsHealthBenefitsRoute = CordycepsHealthBenefitsRouteImport.update({
  id: '/cordyceps-health-benefits',
  path: '/cordyceps-health-benefits',
  getParentRoute: () => rootRouteImport,
} as any)
const CordycepsStudyRoute = CordycepsStudyRouteImport.update({
  id: '/cordyceps-study',
  path: '/cordyceps-study',
  getParentRoute: () => rootRouteImport,
} as any)
const CordycepsVsSinensisRoute = CordycepsVsSinensisRouteImport.update({
  id: '/cordyceps-vs-sinensis',
  path: '/cordyceps-vs-sinensis',
  getParentRoute: () => rootRouteImport,
} as any)
const CultivationTrainingRoute = CultivationTrainingRouteImport.update({
  id: '/cultivation-training',
  path: '/cultivation-training',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchKnowledgeRoute = ResearchKnowledgeRouteImport.update({
  id: '/research-knowledge',
  path: '/research-knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyRadhvanRoute = WhyRadhvanRouteImport.update({
  id: '/why-radhvan',
  path: '/why-radhvan',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/cordycepin': typeof CordycepinRoute
  '/cordyceps-cultivation': typeof CordycepsCultivationRoute
  '/cordyceps-faq': typeof CordycepsFaqRoute
  '/cordyceps-health-benefits': typeof CordycepsHealthBenefitsRoute
  '/cordyceps-study': typeof CordycepsStudyRoute
  '/cordyceps-vs-sinensis': typeof CordycepsVsSinensisRoute
  '/cultivation-training': typeof CultivationTrainingRoute
  '/research-knowledge': typeof ResearchKnowledgeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/why-radhvan': typeof WhyRadhvanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/cordycepin': typeof CordycepinRoute
  '/cordyceps-cultivation': typeof CordycepsCultivationRoute
  '/cordyceps-faq': typeof CordycepsFaqRoute
  '/cordyceps-health-benefits': typeof CordycepsHealthBenefitsRoute
  '/cordyceps-study': typeof CordycepsStudyRoute
  '/cordyceps-vs-sinensis': typeof CordycepsVsSinensisRoute
  '/cultivation-training': typeof CultivationTrainingRoute
  '/research-knowledge': typeof ResearchKnowledgeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/why-radhvan': typeof WhyRadhvanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/cordycepin': typeof CordycepinRoute
  '/cordyceps-cultivation': typeof CordycepsCultivationRoute
  '/cordyceps-faq': typeof CordycepsFaqRoute
  '/cordyceps-health-benefits': typeof CordycepsHealthBenefitsRoute
  '/cordyceps-study': typeof CordycepsStudyRoute
  '/cordyceps-vs-sinensis': typeof CordycepsVsSinensisRoute
  '/cultivation-training': typeof CultivationTrainingRoute
  '/research-knowledge': typeof ResearchKnowledgeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/why-radhvan': typeof WhyRadhvanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/cordycepin'
    | '/cordyceps-cultivation'
    | '/cordyceps-faq'
    | '/cordyceps-health-benefits'
    | '/cordyceps-study'
    | '/cordyceps-vs-sinensis'
    | '/cultivation-training'
    | '/research-knowledge'
    | '/sitemap.xml'
    | '/why-radhvan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/cordycepin'
    | '/cordyceps-cultivation'
    | '/cordyceps-faq'
    | '/cordyceps-health-benefits'
    | '/cordyceps-study'
    | '/cordyceps-vs-sinensis'
    | '/cultivation-training'
    | '/research-knowledge'
    | '/sitemap.xml'
    | '/why-radhvan'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/cordycepin'
    | '/cordyceps-cultivation'
    | '/cordyceps-faq'
    | '/cordyceps-health-benefits'
    | '/cordyceps-study'
    | '/cordyceps-vs-sinensis'
    | '/cultivation-training'
    | '/research-knowledge'
    | '/sitemap.xml'
    | '/why-radhvan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  CordycepinRoute: typeof CordycepinRoute
  CordycepsCultivationRoute: typeof CordycepsCultivationRoute
  CordycepsFaqRoute: typeof CordycepsFaqRoute
  CordycepsHealthBenefitsRoute: typeof CordycepsHealthBenefitsRoute
  CordycepsStudyRoute: typeof CordycepsStudyRoute
  CordycepsVsSinensisRoute: typeof CordycepsVsSinensisRoute
  CultivationTrainingRoute: typeof CultivationTrainingRoute
  ResearchKnowledgeRoute: typeof ResearchKnowledgeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WhyRadhvanRoute: typeof WhyRadhvanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cordycepin': {
      id: '/cordycepin'
      path: '/cordycepin'
      fullPath: '/cordycepin'
      preLoaderRoute: typeof CordycepinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cordyceps-cultivation': {
      id: '/cordyceps-cultivation'
      path: '/cordyceps-cultivation'
      fullPath: '/cordyceps-cultivation'
      preLoaderRoute: typeof CordycepsCultivationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cordyceps-faq': {
      id: '/cordyceps-faq'
      path: '/cordyceps-faq'
      fullPath: '/cordyceps-faq'
      preLoaderRoute: typeof CordycepsFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cordyceps-health-benefits': {
      id: '/cordyceps-health-benefits'
      path: '/cordyceps-health-benefits'
      fullPath: '/cordyceps-health-benefits'
      preLoaderRoute: typeof CordycepsHealthBenefitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cordyceps-study': {
      id: '/cordyceps-study'
      path: '/cordyceps-study'
      fullPath: '/cordyceps-study'
      preLoaderRoute: typeof CordycepsStudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cordyceps-vs-sinensis': {
      id: '/cordyceps-vs-sinensis'
      path: '/cordyceps-vs-sinensis'
      fullPath: '/cordyceps-vs-sinensis'
      preLoaderRoute: typeof CordycepsVsSinensisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cultivation-training': {
      id: '/cultivation-training'
      path: '/cultivation-training'
      fullPath: '/cultivation-training'
      preLoaderRoute: typeof CultivationTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research-knowledge': {
      id: '/research-knowledge'
      path: '/research-knowledge'
      fullPath: '/research-knowledge'
      preLoaderRoute: typeof ResearchKnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-radhvan': {
      id: '/why-radhvan'
      path: '/why-radhvan'
      fullPath: '/why-radhvan'
      preLoaderRoute: typeof WhyRadhvanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  CordycepinRoute: CordycepinRoute,
  CordycepsCultivationRoute: CordycepsCultivationRoute,
  CordycepsFaqRoute: CordycepsFaqRoute,
  CordycepsHealthBenefitsRoute: CordycepsHealthBenefitsRoute,
  CordycepsStudyRoute: CordycepsStudyRoute,
  CordycepsVsSinensisRoute: CordycepsVsSinensisRoute,
  CultivationTrainingRoute: CultivationTrainingRoute,
  ResearchKnowledgeRoute: ResearchKnowledgeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WhyRadhvanRoute: WhyRadhvanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
